### ISSUE TITLE
Problem using it on a different process (unity win x64)

### ISSUE THREAD

**Issue by schealex** [hackf5/unityspy#18]
Hi there,

first of all this is a really crazy and cool project and might help me out a lot as i've been struggeling to get data from the game my current project it about.

So right now i'm trying to get it working but it throws this exception right from the point where i select the process:

```
Game executable file closed, unity version = 2020.3.31.7034039.
The unity version the process is running (2020.3.31 in 64 bits mode) is not supported.
Offsets of 2020.3.13 selected instead.
System.ArgumentNullException: Value cannot be null. (Parameter 'moduleInfo')
   at HackF5.UnitySpy.ProcessFacade.ProcessFacade.ReadModule(ModuleInfo moduleInfo) in C:\dev\github.com\unityspy\src\HackF5.UnitySpy\ProcessFacade\ProcessFacade.cs:line 164
   at HackF5.UnitySpy.ProcessFacade.UnityProcessFacade.ReadModule(ModuleInfo moduleInfo) in C:\dev\github.com\unityspy\src\HackF5.UnitySpy\ProcessFacade\UnityProcessFacade.cs:line 59
   at HackF5.UnitySpy.AssemblyImageFactory.Create(UnityProcessFacade process, String assemblyName) in C:\dev\github.com\unityspy\src\HackF5.UnitySpy\AssemblyImageFactory.cs:line 35
   at HackF5.UnitySpy.Gui.Avalonia.ViewModel.MainWindowViewModel.BuildImageAsync() in C:\dev\github.com\unityspy\src\HackF5.UnitySpy.Gui.Avalonia\ViewModel\MainWindowViewModel.cs:line 355
```

I've tried to debug though it and it seems it's trying to find `mono-2.0-bdwgc.dll` in the game process but that does not exist.

Any help on this is greatly appreciated!

**Comment by sebastientromp** [comment]
What game is it for? And you probably will have more luck asking on the Discord (the link is in the readme I think), as others will be able to help as well.
